### ISSUE TITLE
RFC Do not embed the i2c bus in the driver struct

### ISSUE THREAD

**Issue by pyaillet** [nebelgrau77/pcf8563-rs#2]
Hi !

Thank you again for making this project.

I am creating this issue to open a discussion on some architectural details of the driver.

Currently, the i2c bus struct used to communicate with the device is taken by the driver at creation, making it a bit complex to use it in the context of a shared i2c bus.
I used to try the [shared-bus](https://github.com/Rahix/shared-bus) project to deal with this, but it didn't feel right because it was pushing platform locking details inside the drivers.

On [another driver project](https://github.com/pyaillet/grove-matrix-led-my9221-rs), I tried another approach by pushing away this outside of the driver. 
The driver does not take the i2c bus at creation, but get a mutable ref to the bus on each function where it's needed.

I think that by doing this rust makes sure for us that during the function execution there won't be any other &mut to the i2c bus (giving us a kind of implicit section mutex) while pushing the details on how we get the &mut outside of the driver and being taken care at the platform level.

I would really be happy to have your feedback on this, I might have missed some points as I am still a bit new with rust and embedded.

Anyway thank you for your time reading this :)

**Comment by nebelgrau77** [comment]
Hello!

Thank you for your interest in this driver, and your interesting insights! I have to admit that even though I understand the issue, it's kind of pushing the boundaries of my Rust, embedded, and embedded Rust knowledge :) 

I often use shared-bus, including with this driver. I made a simple desk clock using PCF8563 and the Akafugu 7-segment display, I can share the code (I should probably add it as an example, actually). But I didn't think about those platform-specific details. 

So what you're proposing in the LED matrix driver is to have the driver take the i2c bus every time it has to use it, is that correct?  I wonder how often it is used: most drivers I have used so far (displays, IMUs) seem to "embed" the bus, which of course doesn't mean that it is the only, or the best way to do it. 
Do you know other drivers that implement this solution? I based mine on existing drivers by other people, so I guess I also "inherited" some ways of doing things, without fully understanding all the implications. But what you're saying sounds interesting and makes a lot of sense to me. Unfortunately I lack in expertise to give you a more constructive feedback (or find any "holes" in the concept). 

This is probably something to ask in the embedded-rust matrix channel :)

I will think about it some more!

**Comment by pyaillet** [comment]
I asked the question on in the embedded-rust matrix channel, and got a link to [this article](https://blog.rahix.de/001-shared-bus/) which gives interesting input on this subject.

I will give a try to this approach and close this issue.

Anyway thank you for the feedback !

**Comment by nebelgrau77** [comment]
Interesting! Thanks for the article!
